app:
  env: test
  name: go-mall
  log:
    path: "/home/applog/go-mall/go-mall.log"
    max_size: 100 # 单个日志文件最大100M
    max_age: 60 # 备份文件最多保存60天
  pagination:
    default_size: 20
    max_size: 100
  wechat_pay:
    appid: ""
    mchid: ""
    private_serial_no: "" # 证书序列号
    aes_key: ""
    notify_url: "" # 支付结果回调通知地址
database:
  master:
    type: mysql
    #通过k8s service name连接, 在k8s集群内的管理 mysql pod的service名是mysql
    dsn: root:superpass@tcp(mysql:3306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000000 # 300s 内可复用
  slave:
    type: mysql
    dsn: root:superpass@tcp(mysql:3306)/go_mall?charset=utf8&parseTime=True&loc=Asia%2FShanghai
    maxopen: 100
    maxidle: 10
    maxlifetime: 300000000000
redis:
  addr: redis:6379 #通过k8s service name连接, 在k8s集群内的管理 redis pod的service名是redis
  password: 123456
  pool_size: 10
  db: 1